---
# remember to change image-name and repo-name

name: Publish Docker Image
on:
  push: # generate image whenever there is a push to the listed branches
    branches:
      - master
  release: # generate images for releases, using the tag name; the newest one will be latest
    types: [published]
jobs:
  push_to_registry:
    # only generate images when in the named repo (to avoid running the action in forks)
    if: github.repository == 'scilifelabdatacentre/repo-name'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      # prepare qemu and buildx to enable multi-architecture builds
      - name: Run setup-qemu-action
        uses: docker/setup-qemu-action@v2
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@v1
      # only needed when publishing to Dockerhub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # available in scilifelabdatacentre, ask admin for help
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}}
      # only needed when publishing to Github (ghcr.io)
      - name: Log in to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # will run as the user who triggered the action, using its token
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            # list of all images that will be pushed
            ghcr.io/scilifelabdatacentre/image-name # github
            docker.io/scilifelabdatacentre/image-name # dockerhub
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # the qemu and buildx steps can be skipped if arm is removed
