---
# Perform Python code linting using black
# Remember to change "./code-folder" to the folder with the code
name: Black formatting

on: [push, pull_request]

jobs:
  BlackFormatting:
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Check code formatting with Black
        uses: psf/black@stable
        with:
          options: "-l 100 --check"
          src: "./code-folder"
